# __Superstore Data Analysis__

In [69]:
import numpy as np
import pandas as pd

In [70]:
df = pd.read_csv('/content/superstore_final_dataset.csv')
df.head(2)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

In [71]:
df.shape

(9800, 18)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         9800 non-null   int64
 1   Order_ID       9800 non-null   object
 2   Order_Date     9800 non-null   object
 3   Ship_Date      9800 non-null   object
 4   Ship_Mode      9800 non-null   object
 5   Customer_ID    9800 non-null   object
 6   Customer_Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal_Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product_ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub_Category   9800 non-null   object
 16  Product_Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [73]:
new_dict = {}
for col in df.columns:
  new_dict.update({col: df[col].nunique()})

unique_dict =  pd.DataFrame(new_dict, index=['Unique'])
unique_dict

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
Unique,9800,4922,1230,1326,4,793,793,3,1,529,49,626,4,1861,3,17,1849,5757

## Removing unwanted column(s)

In [74]:
df.drop(['Row_ID', 'Country'], axis = 1, inplace = True)
df.head(2)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

## Removing duplicate rows ( there could be duplicate rows excluding Row_ID column ).

In [75]:
df[df.duplicated()]

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
3406,US-2015-150119,23/04/2015,27/04/2015,Standard Class,LB-16795,Laurel Beltran,Home Office,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372

In [76]:
df.drop_duplicates(inplace = True, ignore_index = True)
df.head(2)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

In [77]:
df.shape

(9799, 16)

## Removing rows for which few values are missing.

In [78]:
df.isna().sum()

Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
City              0
State             0
Postal_Code      11
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
dtype: int64

In [79]:
df.dropna(inplace = True)
df.head(2)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

In [80]:
df.shape

(9788, 16)

## Remove irrelevant values from each column if any. Validation of all values for a column( order date and ship date value must be in correct date format ). For each entry in dataset ship date >= order date

### Transforming to correct datatype

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9788 entries, 0 to 9798
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       9788 non-null   object
 1   Order_Date     9788 non-null   object
 2   Ship_Date      9788 non-null   object
 3   Ship_Mode      9788 non-null   object
 4   Customer_ID    9788 non-null   object
 5   Customer_Name  9788 non-null   object
 6   Segment        9788 non-null   object
 7   City           9788 non-null   object
 8   State          9788 non-null   object
 9   Postal_Code    9788 non-null   float64
 10  Region         9788 non-null   object
 11  Product_ID     9788 non-null   object
 12  Category       9788 non-null   object
 13  Sub_Category   9788 non-null   object
 14  Product_Name   9788 non-null   object
 15  Sales          9788 non-null   float64
dtypes: float64(2), object(14)
memory usage: 1.3+ MB

In [82]:
df = df.astype({'Order_Date': 'datetime64[ns]', 'Ship_Date': 'datetime64[ns]', 'Postal_Code': 'int'})
df['Postal_Code'] = df['Postal_Code'].map(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9788 entries, 0 to 9798
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       9788 non-null   object
 1   Order_Date     9788 non-null   datetime64[ns]
 2   Ship_Date      9788 non-null   datetime64[ns]
 3   Ship_Mode      9788 non-null   object
 4   Customer_ID    9788 non-null   object
 5   Customer_Name  9788 non-null   object
 6   Segment        9788 non-null   object
 7   City           9788 non-null   object
 8   State          9788 non-null   object
 9   Postal_Code    9788 non-null   object
 10  Region         9788 non-null   object
 11  Product_ID     9788 non-null   object
 12  Category       9788 non-null   object
 13  Sub_Category   9788 non-null   object
 14  Product_Name   9788 non-null   object
 15  Sales          9788 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(13)
memory usage: 1.3+ MB

### Checking weather Ship_Date < Order_Date

In [83]:
# Ship_Date < Order_Date -> 1684 rows
df.loc[df['Ship_Date'] < df['Order_Date']].head(2)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
2,CA-2017-138688,2017-12-06,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775

In [84]:
df['Ship_Mode'].value_counts()

Standard Class    5848
Second Class      1901
First Class       1501
Same Day           538
Name: Ship_Mode, dtype: int64

In [85]:
# Error when the 'Ship_Mode' is 'Second Class' -> 305 rows
df.loc[(df['Ship_Mode'] == 'Second Class') & (df['Ship_Date'] < df['Order_Date'])].head(2)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
2,CA-2017-138688,2017-12-06,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62
18,CA-2015-143336,2015-08-27,2015-01-09,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,San Francisco,California,94109,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.56

In [86]:
# Error when the 'Ship_Mode' is 'First Class' -> 157 rows
df.loc[(df['Ship_Mode'] == 'First Class') & (df['Ship_Date'] < df['Order_Date'])].head(2)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
44,CA-2017-118255,2017-11-03,2017-03-13,First Class,ON-18715,Odella Nelson,Corporate,Eagan,Minnesota,55122,Central,TEC-AC-10000171,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,45.98
45,CA-2017-118255,2017-11-03,2017-03-13,First Class,ON-18715,Odella Nelson,Corporate,Eagan,Minnesota,55122,Central,OFF-BI-10003291,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,17.46

In [87]:
# Error when the 'Ship_Mode' is 'Same Day' -> 2 rows
df.loc[(df['Ship_Mode'] == 'Same Day') & (df['Ship_Date'] < df['Order_Date'])]

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
8768,CA-2017-151148,2017-12-09,2017-09-13,Same Day,PO-19180,Philisse Overcash,Home Office,Louisville,Colorado,80027,West,TEC-PH-10001870,Technology,Phones,Lunatik TT5L-002 Taktik Strike Impact Protecti...,146.952
8769,CA-2017-151148,2017-12-09,2017-09-13,Same Day,PO-19180,Philisse Overcash,Home Office,Louisville,Colorado,80027,West,FUR-CH-10002304,Furniture,Chairs,"Global Stack Chair without Arms, Black",83.136

In [88]:
# Error when the 'Ship_Mode' is 'Standard Class' -> 1220 rows
df.loc[(df['Ship_Mode'] == 'Standard Class') & (df['Ship_Date'] < df['Order_Date'])].head(2)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
3,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

### Removing rows where 'Ship_Date' < 'Order_Date'

In [89]:
df = df.loc[df['Ship_Date'] >= df['Order_Date']]
df.shape

(8104, 16)

In [90]:
df.reset_index(drop = True, inplace = True)
df.head(2)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

## Export the cleaned dataset as a .csv file: prefer UTF-8 encoding.

In [93]:
# df.to_csv('Superstore_v2.csv', encoding='utf-8')